const Test = require("../models/testModel");
const Question = require("../models/questionModel");
const User = require("../models/userModel");
const SeedFlag = require("../models/seedFlagModel");
const { TEST_FORMATS } = require("./testFormats");

// ── PYQ: LEET 2024 — B.Tech (Lateral Entry for Diploma Holders) ──────────────
// The full 100-question 2024 paper, reproduced faithfully as an interactive
// MCQ set (a real past paper — high-value and safe to reproduce). Shipped as a
// PRACTICE-mode "Exam Ready" (real-exam / 100 Q) test so the correct option is
// revealed the moment a student ticks an answer. Every question keeps its four
// original options in the original a/b/c/d order; the correct answer was solved
// and cross-checked (the numeric ones verified symbolically).
//
// A few questions in the original paper are ambiguous or contain an obvious
// slip; where so, the note explains the intended reading and we keep the most
// defensible key (staff can adjust any of these live in the Content Studio):
//   • Q26 — f'(a)=0 is necessary but not sufficient; option (a) is arguably also
//           false, but the keyed converse (c) is the standard "false" statement.
//   • Q36 — with 5 + 3 balls the separated colour must be the 3; the constraint
//           is taken as "no two RED together" so the paper's key (1440) holds.
//   • Q70 — milk is the colloid; the intended "not a colloid" is the NaCl true
//           solution (water/iron are elements/compounds, not the tested contrast).
//   • Q98 — a stray "Frog: Aestivation" fragment (belongs to Q100) is dropped.

const SEED_KEY = "leet-2024-pyq-v1";

const q = (text, options, correctIndex, explanation, subject, topic) => ({
    text,
    options,
    correctIndex,
    explanation,
    subject,
    topic,
});

const LEET_2024 = [
    // ── Engineering Mechanics / Strength of Materials / Physics (Q1–Q25) ──
    q("A man holds a book weighing 5 N between his hands and keeps it from falling by pressing both hands against the book with a force of 10 N each. The coefficient of friction between the book and the hands would be ________.",
        ["0.15", "0.25", "0.45", "0.8"], 1,
        "Friction from both hands must support the weight: 2·μ·10 = 5 ⟹ μ = 0.25.",
        "Engineering Mechanics", "Friction"),
    q("The magnitude of the shear stress induced in a solid shaft due to an applied torque varies ________.",
        ["From maximum at the centre to zero at the circumference", "From zero at the centre to maximum at the circumference", "From maximum at the centre to minimum at the circumference and not zero", "From minimum at the centre and not zero to maximum at the circumference"], 1,
        "τ = T·r/J, so shear stress is zero on the axis and maximum at the outer surface.",
        "Strength of Materials", "Torsion"),
    q("A hollow shaft of the same cross-sectional area as that of a solid shaft can ________.",
        ["resist less torque", "resist more torque", "resist equal torque", "none of the above"], 1,
        "For the same area the hollow shaft has a larger polar moment of inertia, so it resists more torque.",
        "Strength of Materials", "Torsion"),
    q("The equivalent length of a column fixed at both the ends is ________.",
        ["0.7 L", "0.5 L", "L", "2 L"], 1,
        "Both ends fixed ⟹ effective length = 0.5 L.",
        "Strength of Materials", "Columns"),
    q("The principal stresses σ1, σ2 and σ3 at a point are 80 MPa, 30 MPa and −40 MPa respectively. The maximum shear stress is ________.",
        ["25 MPa", "35 MPa", "55 MPa", "60 MPa"], 3,
        "τ_max = (σ_max − σ_min)/2 = (80 − (−40))/2 = 60 MPa.",
        "Strength of Materials", "Principal Stresses"),
    q("Which one of the following is the preferable cross-section of a beam for bending loads?",
        ["Circular", "Annular circular", "Rectangular", "I-section"], 3,
        "The I-section keeps most material far from the neutral axis, giving the highest section modulus for bending.",
        "Strength of Materials", "Bending"),
    q("A particle starts from rest and moves in a straight line whose equation of motion is S = 2t³ − t² − 1. The acceleration of the particle after three seconds will be ________.",
        ["40 m/s²", "60 m/s²", "28 m/s²", "34 m/s²"], 3,
        "a = d²S/dt² = 12t − 2; at t = 3 s, a = 34 m/s².",
        "Engineering Mechanics", "Kinematics"),
    q("A rubber ball is thrown vertically upward with a velocity u from the top of a building. It strikes the ground with a velocity 3u. The time taken by the ball to reach the ground is ________.",
        ["4u/g", "3u/g", "2u/g", "u/g"], 0,
        "Taking up as positive: −3u = u − g·t ⟹ t = 4u/g.",
        "Engineering Mechanics", "Kinematics"),
    q("During an inelastic collision of two particles, which one of the following is conserved?",
        ["total linear momentum only", "total kinetic energy only", "both linear momentum and kinetic energy", "neither linear momentum nor kinetic energy"], 0,
        "Momentum is always conserved in a collision; kinetic energy is not conserved when the collision is inelastic.",
        "Engineering Mechanics", "Collisions"),
    q("The moment of inertia of a triangular section of base 'a' and height 'L' about an axis passing through its CG and parallel to the base is ________.",
        ["aL³/36", "aL³/6", "aL³/8", "aL³/12"], 0,
        "For a triangle, I about the centroidal axis parallel to the base is bh³/36 = aL³/36.",
        "Engineering Mechanics", "Moment of Inertia"),
    q("The forces which meet at one point and have their lines of action in different planes are called ________.",
        ["Intersecting forces", "Non-coplanar non-concurrent forces", "Coplanar non-concurrent forces", "Non-coplanar concurrent forces"], 3,
        "Meeting at a point ⟹ concurrent; lines of action in different planes ⟹ non-coplanar.",
        "Engineering Mechanics", "Force Systems"),
    q("What is the magnitude of the resultant of two like parallel forces 10 N and 30 N separated by a distance of 10 cm?",
        ["20√2 N", "10√10 N", "20 N", "40 N"], 3,
        "Like parallel forces simply add: 10 + 30 = 40 N.",
        "Engineering Mechanics", "Force Systems"),
    q("Which one of the following forces is a contact force?",
        ["Force of gravity", "Magnetic force", "Force of friction", "Electrostatic force"], 2,
        "Friction acts only where surfaces touch; the others act at a distance.",
        "Engineering Mechanics", "Forces"),
    q("Which of the following is CORRECT for an indeterminate beam condition?",
        ["Number of unknown components should be equal to the number of equilibrium equations", "Number of unknown components should be less than the number of equilibrium equations", "Number of unknown components should be greater than the number of equilibrium equations", "Number of unknown components should be zero"], 2,
        "A beam is statically indeterminate when the unknown reactions exceed the available equilibrium equations.",
        "Strength of Materials", "Beams"),
    q("A triangular shaped frame is a/an ________ frame.",
        ["redundant", "imperfect", "deficient", "perfect"], 3,
        "A triangle satisfies m = 2j − 3, so it is a perfect (just-rigid) frame.",
        "Engineering Mechanics", "Trusses"),
    q("A block of mass 5 kg slides down from rest along a frictionless inclined plane that makes an angle of 30° with the horizontal. What will be the speed of the block after it covers a distance of 3.6 m along the plane? [g = 10 m/s²]",
        ["5 m/s", "6 m/s", "7 m/s", "8 m/s"], 1,
        "a = g·sin30° = 5 m/s²; v = √(2·a·s) = √(2·5·3.6) = 6 m/s.",
        "Engineering Mechanics", "Dynamics"),
    q("A thin disc and a thin ring both have mass M and radius R. Both rotate about axes through their centre of mass perpendicular to their surfaces at the same angular velocity. Which of the following is true?",
        ["The ring has higher kinetic energy", "The disc has higher kinetic energy", "The ring and the disc have the same kinetic energy", "Kinetic energies of both bodies are zero since they are not in linear motion"], 0,
        "I_ring = MR² > I_disc = ½MR²; at equal ω, KE = ½Iω², so the ring has more.",
        "Engineering Mechanics", "Rotation"),
    q("The free body diagram of a body shows the body ________.",
        ["with its surroundings and external forces acting on it", "isolated from all external forces", "isolated from all surroundings", "isolated from its surroundings and all external effects acting on it"], 3,
        "An FBD shows the body isolated from its surroundings with all the external forces/effects acting on it.",
        "Engineering Mechanics", "Statics"),
    q("Which of the following produces the least friction?",
        ["Sliding friction", "Rolling friction", "Static friction", "Same in static and dynamic friction"], 1,
        "Rolling friction is the smallest of these.",
        "Engineering Mechanics", "Friction"),
    q("A book of mass 10 kg is lying on the front desk of a classroom. The coefficient of static friction is 0.5. A force of 40 N is applied to the book. The book will ________.",
        ["move", "will not move", "cannot say", "none of the above"], 1,
        "Limiting friction = μ·mg ≈ 0.5·10·9.8 = 49 N > 40 N, so the book stays put.",
        "Engineering Mechanics", "Friction"),
    q("A body of weight 'W' is required to move up a rough inclined plane whose angle of inclination with the horizontal is 'α'. The effort applied parallel to the plane is given by (μ = tanφ = coefficient of friction between the plane and the body) ________.",
        ["P = W tanα", "P = W tan(α + φ)", "P = W(sinα + μcosα)", "P = W(cosα + μsinα)"], 2,
        "For effort parallel to the incline, P = W(sinα + μcosα).",
        "Engineering Mechanics", "Friction"),
    q("The sum of the magnitudes of two forces acting at a point is 16 N. If the resultant force is 8 N and its direction is perpendicular to the smaller force, then the forces are ________.",
        ["6N and 10N", "8N and 10N", "6N and 12N", "10N and 10N"], 0,
        "With P + Q = 16 and the 8 N resultant ⟂ to the smaller force, Q² = P² + 8² gives P = 6 N, Q = 10 N (a 6-8-10 triangle).",
        "Engineering Mechanics", "Force Systems"),
    q("The maximum deflection for a cantilever beam of span L, loaded at the free end by a force P, is given by ________.",
        ["PL²/3EI", "PL²/6EI", "PL³/8EI", "PL³/3EI"], 3,
        "Free-end deflection of an end-loaded cantilever is PL³/3EI.",
        "Strength of Materials", "Deflection"),
    q("Calculate Young's Modulus of Elasticity of a material whose bulk modulus is 50 GPa, modulus of rigidity is 30 GPa and Poisson's ratio is 0.25.",
        ["75 GPa", "110 GPa", "60 GPa", "90 GPa"], 0,
        "E = 9KG/(3K + G) = 9·50·30/(150 + 30) = 75 GPa.",
        "Strength of Materials", "Elastic Constants"),
    q("Compared with a solid section, a hollow section column has ________.",
        ["High buckling strength", "Low buckling strength", "Same buckling strength", "None of the above"], 0,
        "For the same area a hollow section has a larger radius of gyration, hence higher buckling strength.",
        "Strength of Materials", "Columns"),

    // ── Mathematics (Q26–Q50) ──
    q("Which of the following is false?",
        ["f(a) is an extreme value of f(x) if f '(a) = 0", "If f(a) is an extreme value of f(x), then f '(a) = 0", "If f '(a) = 0, then f(a) is an extreme value of f(x)", "None of these"], 2,
        "f '(a) = 0 is necessary but not sufficient for an extremum (e.g. f(x) = x³ at x = 0), so this converse is false.",
        "Mathematics", "Calculus"),
    q("For what value of λ do the simultaneous equations 4x + 3y = 1 and 8x + 6y = λ have infinite solutions?",
        ["λ = 0", "λ = 1", "λ ≠ 2", "λ = 2"], 3,
        "The second equation must be twice the first: λ = 2·1 = 2.",
        "Mathematics", "Linear Equations"),
    q("Stokes' theorem connects ________.",
        ["a line integral and a surface integral", "a surface integral and a volume integral", "a line integral and a volume integral", "the gradient of a function and its surface integral"], 0,
        "Stokes' theorem relates a line integral around a closed curve to a surface integral over the surface it bounds.",
        "Mathematics", "Vector Calculus"),
    q("The family y = Bx + B⁴ of curves is represented by a differential equation of ________ degree.",
        ["1", "2", "3", "4"], 3,
        "Substituting B = y' gives Clairaut's equation y = xy' + (y')⁴; the highest power of y' is 4, so the degree is 4.",
        "Mathematics", "Differential Equations"),
    q("What is the number of ways in which a team of 11 players can be made out of 14 players?",
        ["364", "1001", "1365", "More than one of the above"], 0,
        "¹⁴C₁₁ = ¹⁴C₃ = 364.",
        "Mathematics", "Permutations & Combinations"),
    q("The three vertices of a parallelogram ABCD are A(1, 2, 3), B(−1, −2, −1) and C(2, 3, 2). The coordinates of the fourth vertex D are ________.",
        ["(−2, −3, 0)", "(4, 7, 6)", "(2, 3, 4)", "(2, 2, 3)"], 1,
        "Diagonals bisect each other: D = A + C − B = (4, 7, 6).",
        "Mathematics", "3D Geometry"),
    q("The curve for which the slope of the tangent at any point is equal to the ratio of the abscissa to the ordinate of the point is a/an ________.",
        ["ellipse", "parabola", "circle", "rectangular hyperbola"], 3,
        "dy/dx = x/y ⟹ y² − x² = constant, a rectangular hyperbola.",
        "Mathematics", "Differential Equations"),
    q("The points with position vectors 5î − 2ĵ, 8î − 3ĵ and aî − 15ĵ are collinear if the value of a is ________.",
        ["31", "41", "42", "44"], 3,
        "Equal slopes: (−1)/3 = (−13)/(a − 5) ⟹ a = 44.",
        "Mathematics", "Vectors"),
    q("Multiplication of real-valued square matrices of the same dimension is ________.",
        ["Associative", "Commutative", "Always positive definite", "not always possible to commute"], 0,
        "Matrix multiplication is always associative (though not generally commutative).",
        "Mathematics", "Matrices"),
    q("The value of lim (x→∞) ((x − 1)/(x + 1))^(x + 2) is equal to ________.",
        ["e", "e⁻¹", "e⁻²", "None of these"], 2,
        "((x − 1)/(x + 1))^x → e⁻²; the extra exponent contributes a factor → 1, so the limit is e⁻².",
        "Mathematics", "Limits"),
    q("The number of ways in which 5 white balls and 3 red balls are to be placed around a circle so that no two red balls are placed together is ________.",
        ["1460", "1440", "1420", "1410"], 1,
        "Arrange the 5 white balls in a circle in (5 − 1)! = 24 ways; the 3 red balls go into the 5 gaps in ⁵P₃ = 60 ways ⟹ 24·60 = 1440.",
        "Mathematics", "Permutations & Combinations"),
    q("If u = (x² + y² + z²)^(1/2), then (∂²u/∂x² + ∂²u/∂y² + ∂²u/∂z²) is equal to ________.",
        ["4u", "2/u", "2u", "−u/4"], 1,
        "For u = r, the Laplacian ∇²r = 2/r = 2/u.",
        "Mathematics", "Partial Derivatives"),
    q("The value of the integral ∫₋₂² |1 − x²| dx is ________.",
        ["0", "4", "1", "∞"], 1,
        "Splitting at x = ±1 (where 1 − x² changes sign) and using symmetry gives 4.",
        "Mathematics", "Definite Integrals"),
    q("The integrating factor of the differential equation dy/dx + y·tan x − sec x = 0 is ________.",
        ["cos x", "sec x", "e^(cos x)", "e^(sec x)"], 1,
        "IF = e^(∫tan x dx) = e^(ln sec x) = sec x.",
        "Mathematics", "Differential Equations"),
    q("The modulus of the eigenvalues of an orthogonal matrix is ________.",
        ["0", "−1", "1", "2"], 2,
        "Orthogonal matrices preserve length, so every eigenvalue has modulus 1.",
        "Mathematics", "Matrices"),
    q("Which one of the following statements is true for all real symmetric matrices?",
        ["All the eigenvalues are real", "All the eigenvalues are positive", "All the eigenvalues are distinct", "Sum of all the eigenvalues is zero"], 0,
        "A real symmetric matrix always has real eigenvalues.",
        "Mathematics", "Matrices"),
    q("The value of lim (x→∞) 2x·sin(4/x) is ________.",
        ["2", "4", "8", "1"], 2,
        "As x → ∞, sin(4/x) ≈ 4/x, so 2x·(4/x) = 8.",
        "Mathematics", "Limits"),
    q("When the height of a building is equal to the length of its shadow, what is the angle of elevation of the Sun?",
        ["30°", "45°", "90°", "60°"], 1,
        "tanθ = height/shadow = 1 ⟹ θ = 45°.",
        "Mathematics", "Trigonometry"),
    q("Find the value of sin(1920°).",
        ["1/2", "1/√2", "√3/2", "1/3"], 2,
        "1920° − 5·360° = 120°, and sin120° = √3/2.",
        "Mathematics", "Trigonometry"),
    q("If 3x² + ax + 4 is perfectly divisible by x − 5, then the value of a is ________.",
        ["−12", "−5", "−15.8", "−14.5"], 2,
        "By the factor theorem, 3(25) + 5a + 4 = 0 ⟹ a = −15.8.",
        "Mathematics", "Polynomials"),
    q("If we add two irrational numbers, the resulting number ________.",
        ["is always a rational number", "is always an irrational number", "may be a rational or an irrational number", "is always an integer"], 2,
        "e.g. √2 + (−√2) = 0 (rational) but √2 + √2 = 2√2 (irrational).",
        "Mathematics", "Number System"),
    q("The value of the integral ∫₀^(π/2) √sin x / (√sin x + √cos x) dx is ________.",
        ["0", "−π/4", "π/2", "π/4"], 3,
        "Using the King property (x → π/2 − x), 2I = π/2 ⟹ I = π/4.",
        "Mathematics", "Definite Integrals"),
    q("If the order of A is 4×3, the order of B is 4×5 and the order of C is 7×3, then the order of (AᵀB)ᵀCᵀ is ________.",
        ["5 × 3", "4 × 5", "5 × 7", "4 × 3"], 2,
        "AᵀB is 3×5, so (AᵀB)ᵀ is 5×3; Cᵀ is 3×7; the product is 5×7.",
        "Mathematics", "Matrices"),
    q("What is the degree of the equation 1/(X − 3) = 1/(X + 2) − 1/2 ?",
        ["0", "1", "2", "3"], 2,
        "Clearing denominators gives X² − X + 4 = 0, a second-degree equation.",
        "Mathematics", "Equations"),
    q("If the difference between the mode and the median is 4, then find the difference between the median and the mean (in that order).",
        ["2", "1", "3", "4"], 0,
        "Mode = 3·Median − 2·Mean ⟹ Mode − Median = 2(Median − Mean) ⟹ 4 = 2·(2).",
        "Mathematics", "Statistics"),

    // ── Computer awareness (Q51–Q57) ──
    q("Which function key is used for opening Help?",
        ["F1", "F2", "F4", "F3"], 0,
        "F1 opens Help in most applications.",
        "Computer Awareness", "Shortcuts"),
    q("What is the full form of PNG in the computer image format?",
        ["Printable New Graphic", "Printable New Graphical", "Port Natural Graphics", "Portable Network Graphics"], 3,
        "PNG stands for Portable Network Graphics.",
        "Computer Awareness", "File Formats"),
    q("Which of the following belongs to the category of fourth-generation languages?",
        ["Machine language", "High-level language", "Assembly language", "Query language"], 3,
        "4GLs are high-level, problem-oriented languages such as SQL / query languages.",
        "Computer Awareness", "Programming Languages"),
    q("In a flow chart, the process box is represented by a ________.",
        ["Rectangle", "Diamond", "Parallelogram", "Oval"], 0,
        "A rectangle denotes a process; a diamond is a decision, a parallelogram is I/O, an oval is start/stop.",
        "Computer Awareness", "Flowcharts"),
    q("Representation of the steps to solve a problem with the help of a diagram is known as a ________.",
        ["Graph", "Program", "Algorithm", "Flowchart"], 3,
        "A flowchart is the diagrammatic representation of the steps of a solution.",
        "Computer Awareness", "Flowcharts"),
    q("The sequence of steps written independent of a specific programming language to solve a problem is called a/an ________.",
        ["Coding", "Processing", "Algorithm", "None of the above"], 2,
        "An algorithm is a language-independent, finite sequence of steps that solves a problem.",
        "Computer Awareness", "Algorithms"),
    q("Which of the following is the shortcut key to open a 'New Blank' document in MS-Word?",
        ["CTRL + B", "CTRL + N", "CTRL + D", "CTRL + M"], 1,
        "CTRL + N opens a new blank document.",
        "Computer Awareness", "Shortcuts"),

    // ── Physics / Chemistry / General Science (Q58–Q73) ──
    q("Light year is a unit of ________.",
        ["Time", "Distance", "Light", "Intensity of light"], 1,
        "A light year is the distance light travels in one year.",
        "Physics", "Units & Measurement"),
    q("How much work is done in moving a charge of 5 C across two points having a potential difference of 16 V?",
        ["65 J", "45 J", "40 J", "80 J"], 3,
        "W = qV = 5·16 = 80 J.",
        "Physics", "Electrostatics"),
    q("A car A is moving with a speed of 40 km/h. Another car B is moving with 60 km/h in the opposite direction to car A. What will be the relative speed of car B with respect to car A?",
        ["40 km/h", "60 km/h", "100 km/h", "20 km/h"], 2,
        "Opposite directions ⟹ relative speed = 40 + 60 = 100 km/h.",
        "Physics", "Kinematics"),
    q("The area under a velocity-time graph gives ________.",
        ["acceleration", "total distance travelled", "speed", "retardation"], 1,
        "The area under a v-t graph equals the distance travelled.",
        "Physics", "Kinematics"),
    q("A sphere P impinges directly on another identical sphere Q at rest. If the coefficient of restitution is 0.5, the ratio of velocities Vq/Vp after the impact would be ________.",
        ["1 : 1", "2 : 1", "3 : 1", "2 : 3"], 2,
        "For equal masses Vp = u(1 − e)/2 and Vq = u(1 + e)/2, so Vq/Vp = (1 + e)/(1 − e) = 1.5/0.5 = 3.",
        "Engineering Mechanics", "Collisions"),
    q("Strain in a given material is the ratio of ________.",
        ["applied load to the area of cross-section opposing the load", "change in dimension to the original dimension", "applied load to the original dimension", "change in dimension to the area of cross-section opposing the load"], 1,
        "Strain = change in dimension / original dimension (dimensionless).",
        "Strength of Materials", "Stress & Strain"),
    q("A man walked 60 m to the East from point A, then turned right and walked 50 m. Finally he turned left and went 60 m and reached point B. Find AB.",
        ["170 meter", "130 meter", "145 meter", "150 meter"], 1,
        "Net East = 60 + 60 = 120 m, net South = 50 m; AB = √(120² + 50²) = 130 m.",
        "Reasoning", "Direction Sense"),
    q("A cubical block rests on an inclined plane of μ = √3. Determine the angle of inclination when the block just slides down the inclined plane.",
        ["40°", "50°", "60°", "20°"], 2,
        "At the point of sliding, tanθ = μ = √3 ⟹ θ = 60°.",
        "Engineering Mechanics", "Friction"),
    q("Water droplets in free fall are spherical due to ________.",
        ["Gravity", "Viscosity", "Surface tension", "Intermolecular attraction"], 2,
        "Surface tension minimises the surface area, giving a spherical shape.",
        "Physics", "Surface Tension"),
    q("A position-dependent force F = 7 − 2x + 3x² N acts on a small body of mass 2 kg and displaces it from x = 0 to x = 5 m. The work done, in joules, is ________.",
        ["135", "270", "35", "70"], 0,
        "W = ∫₀⁵ (7 − 2x + 3x²) dx = 35 − 25 + 125 = 135 J.",
        "Physics", "Work & Energy"),
    q("The chemical name of washing soda is ________.",
        ["Sodium chloride", "Sodium hydrogen carbonate", "Sodium carbonate", "Sodium hydroxide"], 2,
        "Washing soda is sodium carbonate decahydrate, Na₂CO₃·10H₂O.",
        "Chemistry", "Chemical Compounds"),
    q("Which is the most abundant metal in the human body?",
        ["Zinc", "Iron", "Magnesium", "Calcium"], 3,
        "Calcium, mostly in bones and teeth, is the most abundant metal in the body.",
        "Chemistry", "Biochemistry"),
    q("Which one of the following is not a colloid?",
        ["Aqueous solution of NaCl", "Milk", "Water", "Iron"], 0,
        "An aqueous NaCl solution is a true solution, not a colloid (milk is the colloid in the list).",
        "Chemistry", "Colloids"),
    q("At which point of the Earth is there no gravity?",
        ["At the North and South Pole", "At the equator", "On the ocean surface", "At the centre of the Earth"], 3,
        "At the centre, mass pulls equally in all directions, so the net gravitational force is zero.",
        "Physics", "Gravitation"),
    q("Which force moves an aircraft through the air?",
        ["Lift Force", "Drag Force", "Thrust Force", "Gravity Force"], 2,
        "Thrust from the engines propels the aircraft forward.",
        "Physics", "Forces"),
    q("Why are the soles of shoes treaded?",
        ["To give the shoes more protection", "To decrease friction", "To increase friction", "To increase the life of the shoes"], 2,
        "Treads increase grip (friction) to prevent slipping.",
        "Physics", "Friction"),

    // ── Reasoning / Quantitative Aptitude (Q74–Q100) ──
    q("Pointing to a man in a photograph, a man said to a woman, 'His mother is the only daughter of your father.' How is the woman related to the man in the photograph?",
        ["Sister", "Mother", "Wife", "Daughter"], 1,
        "The only daughter of the woman's father is the woman herself, and she is the photo-man's mother.",
        "Reasoning", "Blood Relations"),
    q("In a certain code language, 'kew xas huma deko' means 'she is eating apples', 'kew tepo qua' means 'she sells toys' and 'su lim deko' means 'I like apples'. Which words in that language mean 'she' and 'apples'?",
        ["Xas & deko", "Kew & deko", "Xas & kew", "Kew & xas"], 1,
        "'kew' is common to the first two sentences (she); 'deko' is common to the first and third (apples).",
        "Reasoning", "Coding-Decoding"),
    q("Look at this series: 2, 1, 1/2, 1/4, … What number should come next?",
        ["1/3", "1/8", "2/8", "1/16"], 1,
        "Each term is half the previous one, so the next term = 1/4 ÷ 2 = 1/8.",
        "Reasoning", "Number Series"),
    q("Marks is three times as old as Jacks. 2 years ago, he was five times as old as Jacks. What is the present age of Marks?",
        ["12 years", "14 years", "18 years", "24 years"], 0,
        "M = 3J and M − 2 = 5(J − 2) ⟹ J = 4, M = 12.",
        "Quantitative Aptitude", "Ages"),
    q("Radha keeps all her socks in a single drawer. She has 24 pairs of white socks and 18 pairs of grey socks. Radha picks 3 socks randomly. Find the probability of Radha choosing a matching pair.",
        ["1/36", "1/108", "7/36", "1/1"], 3,
        "With only two colours, any 3 socks must contain at least two of the same colour, so a matching pair is certain (probability 1).",
        "Quantitative Aptitude", "Probability"),
    q("A toy was sold at a profit of 20% on the cost price. If the toy had been sold at 10% lower than this price, the profit would have been Rs. 600 less. At what price should the toy be sold to gain 25% of the cost price?",
        ["7500", "5000", "6250", "7250"], 2,
        "10% of 1.2·CP = 600 ⟹ 0.12·CP = 600 ⟹ CP = 5000; a 25% gain ⟹ 1.25·5000 = 6250.",
        "Quantitative Aptitude", "Profit & Loss"),
    q("Statement: It is desirable to put a child in school at the age of 5 or so.\nAssumptions:\nI. At that age the child reaches an appropriate level of development and is ready to learn.\nII. The schools do not admit children after six years of age.",
        ["Only assumption I is implicit", "Only assumption II is implicit", "Either I or II is implicit", "Neither I nor II is implicit"], 0,
        "I gives the reason behind the recommendation and is implicit; II is not implied by the statement.",
        "Reasoning", "Statement & Assumption"),
    q("Fill in the blank for the given series: SCD, TEF, UGH, ____, WKL.",
        ["CMN", "UJI", "VIJ", "IJT"], 2,
        "First letters S,T,U,V,W; second letters C,E,G,I,K; third letters D,F,H,J,L ⟹ VIJ.",
        "Reasoning", "Alphabet Series"),
    q("What is the number of triangles that can be formed whose vertices are the vertices of an octagon but which have only one side common with the octagon?",
        ["64", "32", "24", "16"], 1,
        "For an n-gon this count is n(n − 4) = 8·4 = 32.",
        "Quantitative Aptitude", "Combinatorics"),
    q("What will come in place of the question mark (?) in the following number series? 5, 7, ?, 25, 45, 75",
        ["11", "13", "15", "19"], 1,
        "Differences are 2, 6, 12, 20, 30 (second differences 4, 6, 8, 10), so ? = 7 + 6 = 13.",
        "Reasoning", "Number Series"),
    q("Complete the analogous pair: Vigilant : Alert :: Viable : ?",
        ["Active", "Hopeless", "Feasible", "Useful"], 2,
        "Vigilant means alert; viable means feasible (synonym relationship).",
        "Reasoning", "Analogy"),
    q("What will come in place of the question mark (?): 121, 222, 424, ?",
        ["646", "828", "626", "524"], 1,
        "The differences 101, 202, 404 double each time, so ? = 424 + 404 = 828.",
        "Reasoning", "Number Series"),
    q("Traffic on a highway is moving at a rate of 360 vehicles per hour at a location. If the number of vehicles arriving follows a Poisson distribution, the probability (rounded to 2 decimal places) that the headway between successive vehicles lies between 6 and 10 seconds is ________.",
        ["0.18", "0.37", "0.85", "0.97"], 0,
        "λ = 360/3600 = 0.1 per second; P(6 ≤ h ≤ 10) = e^(−0.6) − e^(−1.0) ≈ 0.55 − 0.37 = 0.18.",
        "Quantitative Aptitude", "Probability"),
    q("If each side of a square is increased by 25%, find the percentage change in its area.",
        ["65.25", "56.25", "65", "56"], 1,
        "New area = (1.25)² = 1.5625 times the old ⟹ a 56.25% increase.",
        "Quantitative Aptitude", "Percentage"),
    q("Four bells ring simultaneously at the start and then at intervals of 6 s, 12 s, 15 s and 20 s respectively. How many times do they ring together in 2 hours?",
        ["120", "60", "121", "112"], 2,
        "LCM(6,12,15,20) = 60 s, so they coincide every minute; in 120 minutes that is 120 times plus the start = 121.",
        "Quantitative Aptitude", "LCM & HCF"),
    q("Statement: Out of 20 students in a class, 15 passed in English and 18 passed in Mathematics.\nInferences:\nI. There are a few students who passed in both subjects.\nII. No student failed in both subjects.",
        ["Both inferences I and II follow", "Only inference I follows", "Only inference II follows", "Neither inference I nor inference II follows"], 1,
        "15 + 18 − 20 = 13, so at least 13 passed both — inference I follows; II is not guaranteed.",
        "Reasoning", "Logical Inference"),
    q("In a row of boys, A is 13th from the left and D is 17th from the right. If A is 11th from the right in this row, then what is the position of D from the left?",
        ["6th", "7th", "10th", "12th"], 1,
        "Total = 13 + 11 − 1 = 23; D from the left = 23 − 17 + 1 = 7th.",
        "Reasoning", "Ranking & Ordering"),
    q("In a certain code language, the word 'PENCIL' is coded as 'CEILNP'. How is the word 'MOBILE' coded in that language?",
        ["OBELIM", "BEILMO", "LOBMEI", "BOMLEI"], 1,
        "The letters are rearranged into alphabetical order: MOBILE → B, E, I, L, M, O = BEILMO.",
        "Reasoning", "Coding-Decoding"),
    q("How many meaningful four-letter English words can be formed from the second, third, fifth and ninth letters from the left end of the word 'TROPHOGENIST'?",
        ["Two", "None", "Three", "One"], 3,
        "The letters are R, O, H, N, which form only one word: HORN.",
        "Reasoning", "Word Formation"),
    q("If 'elephant' is called 'dog', 'dog' is called 'crow', 'crow' is called 'tiger', 'tiger' is called 'snake' and 'snake' is called 'lion', which is reared as a pet?",
        ["Crow", "Tiger", "Snake", "Elephant"], 0,
        "A dog is reared as a pet, and 'dog' is called 'crow' in this language.",
        "Reasoning", "Coding-Decoding"),
    q("Six persons A, B, C, D, E and F are sitting in two rows, three in each. E is not at the end of any row. D is second to the left of F. C, the neighbour of E, is sitting diagonally opposite to D. B is the neighbour of F. Which of the following pairs is sitting diagonally opposite to each other?",
        ["F and C", "D and A", "A and C", "A and F"], 3,
        "The consistent arrangement (D B F / A E C) places A and F at opposite diagonal corners.",
        "Reasoning", "Seating Arrangement"),
    q("Statements:\nI. Some bottles are bags.\nII. All bags are pencils.\nConclusions:\nI. No bottle is a pencil.\nII. Some bottles are pencils.",
        ["Both conclusions I and II follow", "Neither conclusion I nor conclusion II follows", "Only conclusion I follows", "Only conclusion II follows"], 3,
        "Some bottles are bags and all bags are pencils, so some bottles are pencils (II follows); I contradicts this.",
        "Reasoning", "Syllogism"),
    q("Which is the next number in the series given below? 12, 98, 24, 49, 48, 24.5, ?",
        ["96", "86", "24", "49"], 0,
        "The odd-position terms double (12, 24, 48, 96) while the even-position terms halve (98, 49, 24.5), so the next term is 96.",
        "Reasoning", "Number Series"),
    q("Among 200 people, 90 like tea, 108 like coffee and 46 like both tea and coffee. How many people like neither tea nor coffee?",
        ["46", "44", "62", "48"], 3,
        "Neither = 200 − (90 + 108 − 46) = 200 − 152 = 48.",
        "Quantitative Aptitude", "Sets"),
    q("In a class of 120 students, 40% are females and the rest are males. 50% of the female students passed an entrance exam. If the total number of students who passed the exam is 72, then what percentage of the male students passed the exam?",
        ["33.33%", "66.66%", "16.66%", "52.25%"], 1,
        "Females = 48 (24 passed); males = 72; males who passed = 72 − 24 = 48 ⟹ 48/72 = 66.66%.",
        "Quantitative Aptitude", "Percentage"),
    q("In three of the options, the 2nd number is related to the 1st number in a similar logical way. Which is the odd one out?",
        ["36 − 9", "24 − 6", "42 − 8", "27 − 9"], 2,
        "For 36→9, 24→6 and 27→9 the second number equals the digit sum of the first (3+6=9, 2+4=6, 2+7=9); 42 gives 6, not 8.",
        "Reasoning", "Odd One Out"),
    q("In the following question, select the related word pair from the given alternatives. Bear : Hibernation :: ? : ?",
        ["Man : Immigration", "Bird : Migration", "Food : Adulteration", "Frog : Aestivation"], 3,
        "Hibernation is a bear's winter dormancy; aestivation is a frog's summer dormancy — the same type of relationship.",
        "Reasoning", "Analogy"),
];

// Publish the 2024 LEET PYQ once, as a practice-mode full mock (per-test SeedFlag).
async function ensureLeet2024PyqSeeded() {
    try {
        if (await SeedFlag.exists({ key: SEED_KEY })) return;

        const owner =
            (await User.findOne({ role: { $in: ["superadmin", "admin"] } }).sort({ createdAt: 1 }).select("_id").lean()) ||
            (await User.findOne().sort({ createdAt: 1 }).select("_id").lean());
        if (!owner) {
            console.warn("[leet-2024-pyq] no user to attribute yet; will publish on a later boot");
            return;
        }

        const need = TEST_FORMATS["real-exam"].count; // 100
        if (LEET_2024.length !== need) {
            console.warn(`[leet-2024-pyq] has ${LEET_2024.length} questions, expected ${need} — skipped`);
            return;
        }

        const docs = await Question.insertMany(
            LEET_2024.map((qq) => ({
                text: qq.text,
                options: qq.options,
                correctIndex: qq.correctIndex,
                explanation: qq.explanation,
                subject: qq.subject,
                topic: qq.topic,
                difficulty: "moderate",
                marks: 1,
                createdBy: owner._id,
            }))
        );

        await Test.create({
            title: "PYQ: LEET 2024 — B.Tech Lateral Entry (Diploma Holders)",
            description:
                "The full 100-question 2024 B.Tech Lateral Entry (LEET) paper for diploma holders — Engineering Mechanics, Strength of Materials, Mathematics, Physics, Chemistry, Computer awareness and Reasoning. Practice mode: tick an option and the correct answer is revealed instantly, with a short explanation. (In the real exam each question is +4 marks, −1 for a wrong answer, over 150 minutes for 400 marks.)",
            subject: "PYQ",
            topic: "LEET 2024",
            category: "full-mock",
            format: "real-exam",
            mode: "practice", // tick reveals the correct answer as you go
            durationMinutes: 150,
            targets: [], // a real LEET paper is useful to every student → show to all
            questions: docs.map((d) => d._id),
            totalMarks: docs.length,
            status: "published",
            isPublished: true,
            premium: false, // free by default; staff can flip to premium in one click
            createdBy: owner._id,
        });
        await SeedFlag.create({ key: SEED_KEY });
        console.log(`[leet-2024-pyq] published LEET 2024 PYQ practice test (${docs.length} Q)`);
    } catch (e) {
        console.warn("[leet-2024-pyq] seed skipped:", e.message);
    }
}

module.exports = { LEET_2024, ensureLeet2024PyqSeeded };
